### ISSUE TITLE
Signature deployment is not required?

### ISSUE THREAD

**Issue by dellwatson** [filecoin-project/FEVM-Hardhat-Kit#12]
https://github.com/filecoin-project/FEVM-Hardhat-Kit/blob/6f09818940fe4991335194c0472e45ccfb485601/deploy/00_deploy.js#L43

questionable deployment, because it seems PRIVATE KEY is not needed?
and only require address to deploy? without the possible of signature?

**Comment by ZakAyesh** [comment]
Signatures are required for any transaction on the Filecoin blockchain and FEVM. The above code was just deriving the f4Address from the Ethereum address (which itself is derived from the private key stored securely in your .env file or environment variables).
