### ISSUE TITLE
Error running yarn hardhat get-address

### ISSUE THREAD

**Issue by sharp0s** [filecoin-project/fevm-hardhat-kit#122]
I followed the guide, put my private key into a .env file, and even tried to set it as an environment variable in command prompt, but kept getting this error: `Error HH8: There's one or more errors in your config file:

  * Invalid account: #0 for network: localnet - private key too long, expected 32 bytes
  * Invalid account: #0 for network: hyperspace - private key too long, expected 32 bytes
  * Invalid account: #0 for network: filecoinmainnet - private key too long, expected 32 bytes

To learn more about Hardhat's configuration, please go to https://hardhat.org/config/

For more info go to https://hardhat.org/HH8 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.` Also do I put 0x before the key? I made sure to try it too but I'm still wondering.

**Comment by ZakAyesh** [comment]
Hi, are you putting an Ethereum style private key into the file?
