### ISSUE TITLE
FEVM only works for really small contract size?

### ISSUE THREAD

**Issue by dellwatson** [filecoin-project/fevm-hardhat-kit#13]
I tried to deploy plain erc20, and it seems always revert while takes long time to deploy. 
Is it really not possible to deploy erc20? or just work for small contract size?

tx: 0xef8a307b62473efde1263965b07cfc1129914ab734e8093e8ddad001268d4933

**Comment by Stebalien** [comment]
On wallaby?

**Comment by Stebalien** [comment]
We've had two problems here:

1. Gas estimation was broken, so messages were taking ages to land. That _should_ be fixed.
2. We were aborting when emitting events (not implemented). We _shouldn't_ be reverting now, but I'm not sure what Wallaby is currently running.

**Comment by dellwatson** [comment]
yes on wallaby, I tried again with different simple contract and it works but not plain ERC20
```js
transaction 0x8a7c09a17fe428d94217efec1458c00a58140a282e53b0a3c283fbc2f4ef3954 still pending... It used a gas pricing config of maxPriorityFeePerGas: 197225 maxFeePerGas: 394015 ,
              current gas price is 200690 wei
              
              
✔ Choose what to do with the pending transaction: · increase gas
legacy transaction is not supported
```

**Comment by ZakAyesh** [comment]
Hey @dellwatson are you still having this problem?
