### ISSUE TITLE
Reusing deployed address?

### ISSUE THREAD

**Issue by dellwatson** [filecoin-project/fevm-hardhat-kit#14]
I deploy contract with different address and yet the contract address is still same ?

```
Wallet Ethereum Address: 0xD1244aa84ad5188783721f2D142380F0F1e95088
Wallet f4Address:  f410f2esevkck2umipa3sd4wrii4a6dy6suei4hcukxa
reusing "SimpleCoin" at 0x5A85Bc1Cc4764F5F3f3850Abc3A64D78e6829Fb2
```
is this behaviour intended? and why?

**Comment by ZakAyesh** [comment]
By different address do you mean you are using a new private key? After making a deployment, hardhat stores all the metadata in the "deployments" directory. If you want to redeploy the contracts to new addresses you can use `yarn hardhat deploy --reset`
