### ISSUE TITLE
Error running `yarn hardhat deploy`

### ISSUE THREAD

**Issue by turinglabsorg** [filecoin-project/FEVM-Hardhat-Kit#3]
I'm trying to deploy on wallaby but it fails, not sure what's the error. I added a try catch in my fork and this is the log:

```
nonce: 0
Ethereum deployer address: 0xf403019D93A186a20115806df21C06EB17133303
Send faucet funds to this address (f1): f1zzwgugmqschvmvtp4kqjuadc2yjfaqdhyxr4v4a
Ethereum deployer address (from f0): 0xff000000000000000000000000000000000004ef
priorityFee:  0x30fed
--
--
Deployment data: {
  from: '0xf403019D93A186a20115806df21C06EB17133303',
  args: [],
  gasLimit: 1000000000,
  maxPriorityFeePerGas: '0x30fed',
  nonce: 0,
  log: true
}
Error: IDs must be less than 2^63
```

Never seen the error `IDs must be less than 2^63` and I'm not sure from where it came, can you help someway or there's something I'm doing wrong?

**Comment by rk-rishikesh** [comment]
This is because the nonce is 0. 
You can find the steps to resolve this [here](https://medium.com/@rvk_rishikesh/deploying-your-first-smart-contract-on-fvm-bc4c33e63cf0) for more details.

**Comment by turinglabsorg** [comment]
Thank you I solved, i was missing first transaction.

I'm trying to hack a bit using ethers to send transactions, I've one question because i always receive this error:

I always receive this error: `Transaction hash mismatch from Provider.sendTransaction. (expectedHash="0x05b3d8d3e63f8d4d0955e8fa4173ee519f86591396d12d67de2f82112fea1748", returnedHash="0xb6d6d727966d30d28e2d7177fc6ba1a32a78b0e59634c8ba0b6754b47be3f7aa", code=UNKNOWN_ERROR, version=providers/5.7.1)`

Transactions shows up on the explorer: https://explorer.glif.io/actor/?address=t1s5sa3gv4vmj5fn5oxnnwpq3vpaylnnf4m64f6bq&network=wallabynet

So it's just an "ethers" issue or something is not working correctly? Balance is decreasing correctly when i send FIL to other addresses, but interactions with contract seems not working (trying to send coins using `sendCoin` method).

**Comment by rk-rishikesh** [comment]
It's because the msg.sender value is not your FIL address but the ETH address, and when the contract checks the balance it doesn't check for your FIL address but you ETH address which has zero balance and so it returns false.

**Comment by ZakAyesh** [comment]
Thanks for testing Wallaby and Hardhat kit back when they were both in early development. Both the kit and Wallaby have been updated quite a bit and this problem should now be resolved.
