### ISSUE TITLE
yarn hardhat deploy fails with Transaction hash mismatch

### ISSUE THREAD

**Issue by snissn** [filecoin-project/fevm-hardhat-kit#36]
when i run 
```
yarn hardhat deploy
```
i get an error with the message:

```
Error: Transaction hash mismatch from Provider.sendTransaction. (expectedHash="0x0000000000000000000000000000000000000000000000000000000000000000", returnedHash="0xe133be3e4eb515218f22ae2d9cab918ff38fc434d42bbe2ed892b58b342e488f", code=UNKNOWN_ERROR, version=providers/5.7.2)
error Command failed with exit code 1.
```

I believe that this is the identical problem to what's logged here: 
https://github.com/filecoin-project/lotus/issues/9839
and here:
https://github.com/filecoin-project/ref-fvm/issues/1029

I'm curious if there's ways supported within hardhard to supply the expected tx hash and make this work without the required lotus changes, but also it seems like the lotus changes are set to be confirmed.

Also i'm confused how FEVM-Hardhat-Kit has presumably been working for anyone as this seems to be a major dealbreaker

**Comment by DeveloperAlly** [comment]
Same error for me using hardhat and solidity.

No problem on remix though

**Comment by DeveloperAlly** [comment]
Actually I solved this issue - see here for a really stripped back version of deploying with hardhat https://github.com/DeveloperAlly/typescript-fevm-hardhat-wallaby-deploy-example/blob/main/README.md
