### ISSUE TITLE
StoreAll fails with hardhat and with Remix

### ISSUE THREAD

**Issue by joaosantos15** [filecoin-project/fevm-hardhat-kit#48]
Hey @ZakAyesh, thank you for these examples, they're a great way to get started with the Filecoin solidity libraries.

I went through the hardhat examples. I was able to deploy the contracts, with `yarn hardhat deploy`
<img width="1965" alt="image" src="https://user-images.githubusercontent.com/10178757/213158142-d8eb9cf4-cc3e-4436-a70a-e9879d0c29db.png">

And was also able to run 
```sh
> yarn hardhat store-all --contract "0xDB986b70919537D70C5034c4721C45d8C15c3316" --dealid 774
```

With the output

```sh
> You have both ethereum-waffle and @nomicfoundation/hardhat-chai-matchers installed. They don't work correctly together, so please make sure you only use one.

We recommend you migrate to @nomicfoundation/hardhat-chai-matchers. Learn how to do it here: https://hardhat.org/migrate-from-waffle
Storing data from FilecoinMarketAPI Getter Functions on network hyperspace
(node:68640) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Complete! Deal Label is 0
✨  Done in 7.14s.
```

I then imported the contract to Remix (using metamask as the rpc provider) and tried some of the getters, to check that the data from the deal had been stored, but all the values were uninitialised. I also tried running the StoreAll tx through Remix, but got an error with the gas estimation which caused the transaction to hang forever.

Next, I went to https://hyperspace.filfox.info/en/address/0xDB986b70919537D70C5034c4721C45d8C15c3316 to check the state of the contract and noticed that the StoreAll Txs done through hardhat had reverted and the ones through Remix had run out of gas.

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/10178757/213159021-a3f6c529-e261-432b-9299-7b007200d5db.png">

Any thoughts on how to run the StoreAll tx?

**Comment by ZakAyesh** [comment]
Hi, thanks for bringing this to our attention! There have been several big updates to the testnets that required updating the underlying Filecoin.sol. The repo now posts to the updated Filecoin.sol and FilecoinMarketConsumer has been updated to match with the new API. 

Let me know if it's working for you now! (Please note that deploying via remix is really slow right now so hardhat is probably your best bet).
