### ISSUE TITLE
hyperspace rpc timeout?

### ISSUE THREAD

**Issue by Web3HackerWorld** [filecoin-project/fevm-hardhat-kit#78]
failed to get chainId, falling back on net_version...
Error HH110: Invalid JSON-RPC response received: {"message":"failure to get a peer from the ring-balancer"}

For more info go to https://hardhat.org/HH110 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.

I also try to add timeout for hardhat config ,bug still not work:
```json
{
networks: {
        hyperspace: {
            chainId: 3141,
            url: "https://api.hyperspace.node.glif.io/rpc/v1",
            accounts: [PRIVATE_KEY],
            timeout: 180000,
        },
    },
}
```

**Comment by ZakAyesh** [comment]
This was most likely an issue with the RPC going down during that time frame, that problem should be resolved now (it has been tested). Closing, if this problem persists please feel free to open another issue!
