### ISSUE TITLE
Error executing "store-all" task

### ISSUE THREAD

**Issue by andborges** [filecoin-project/fevm-hardhat-kit#81]
Hi,

Yesterday I was testing this kit and everything went well.
But today I'm trying to execute the "store-all" task with no luck, having this error all the time:

`Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ]`

Nothing changed at my side from yesterday, using pretty much the same deployed smart contract.

Thanks.

**Comment by ZakAyesh** [comment]
Hi @andborges has this problem since been resolved? Using the updated kit everything should be going through.
