### ISSUE TITLE
10000 SimpleCoin missing?

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/FEVM-Hardhat-Kit#9]
Hello, team!

I have followed the README and successfully deployed the SimpleCoin contract. But there seems to be 0 balance in the f0 address. Could you please kindly have a look? Thank you!
Contract:
![image](https://user-images.githubusercontent.com/1591330/198926388-97359bd7-ebbc-4d2e-bd53-e9748d717902.png)
Account: 
![image](https://user-images.githubusercontent.com/1591330/198926481-2493be49-1582-40b5-97d2-0a2040372c1d.png)

**Comment by zixuanzh** [comment]
You need to pass in the msg.sender as the argument for `--account` so replace the 0xff00 address with what `yarn hardhat get-address` returns should work

**Comment by zixuanzh** [comment]
Does it work if you replace the 0xff00 address with what `yarn hardhat get-address` returns?

**Comment by ZakAyesh** [comment]
Thanks for testing Wallaby and Hardhat kit back when they were both in early development. Both the kit and Wallaby have been updated quite a bit and now fully support Ethereum addresses. This function should now work perfect if you put in the Ethereum address of the account that deployed the contract.
