### ISSUE TITLE
ProviderError: cannot parse block param: pending

### ISSUE THREAD

**Issue by ProgramAPE** [filecoin-project/fevm-hardhat-kit#99]

**Comment by ZakAyesh** [comment]
Hi,

Occasionally this occurs, I believe due to the long execution time on Filecoin. Rerunning the command that resulted in this error should fix it. Let me know if it is working for you yet, and please remember to update to the latest version of the kit.

**Comment by ProgramAPE** [comment]
thanks!

**Comment by 1Busayo** [comment]
just change the hyperspace  node url of your  hardhat config file. I used  "https://rpc.ankr.com/filecoin_testnet", visit here for list of hyperspace nodes to switch too (https://chainlist.org/chain/3141?testnets=true)
